name: elapid

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.7
  - descartes
  - gdal
  - geopandas
  - glmnet
  - matplotlib
  - pandas
  - rasterio>=1.0
  - rtree
  - scikit-learn
  - shapely
  - tqdm
  - pip
  - pip:
    - -r requirements.txt
    - mkdocs-material
    - mkdocs-jupyter
    - mkdocstrings
