name: elapid

channels:
  - conda-forge
  - defaults

dependencies:
  - python>3.7
  - black
  - descartes
  - flake8
  - gdal
  - geopandas
  - glmnet
  - isort
  - matplotlib
  - pandas
  - pre-commit
  - pytest
  - pytest-cov
  - rasterio
  - rtree
  - scikit-learn
  - scipy
  - shapely
  - tqdm
  - pip
  - pip:
    - -r requirements.txt
    - mkdocs-material
    - mkdocs-jupyter
    - mkdocstrings
