name: elapid

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.7
  - descartes
  - gdal
  - geopandas
  - glmnet
  - matplotlib
  - pandas
  - rasterio
  - rtree
  - scikit-learn
  - scipy
  - shapely
  - tqdm
  - pip
  - pip:
    - -r requirements.txt
