name: docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: $CONDA/bin/conda env update --file environment.yml --name base
      - run: $CONDA/bin/pip install .
      - run: $CONDA/bin/mkdocs gh-deploy --force
