name: docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: $CONTAINER
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install .
      - run: pip install mkdocs-material mkdocs-jupyter mkdocstrings
      - run: mkdocs gh-deploy --force
