name: docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.x
      - run: make init
      - run: conda run -n elapid gh-deploy --force
